#!/bin/bash

CGROUP=/sys/fs/cgroup
CPU_GRP=$CGROUP/cpuset/plumber
# RDT_GRP=$CGROUP/intel_rdt/plumber

CPUS=$CPU_GRP/cpuset.cpus
MEMS=$CPU_GRP/cpuset.mems
CPU_EXC=$CPU_GRP/cpuset.cpu_exclusive
MIGRATE=$CPU_GRP/cpuset.memory_migrate

MOC=~/workspace/moc
PERF=~/bin/perf
CACHE_DRIVER="python $MOC/etc/cache_driver.py"
# CACHE=$RDT_GRP/intel_rdt.cache_mask
# OTHERS_CACHE=$CGROUP/intel_rdt/intel_rdt.cache_mask

op=$1
shift

case "$op" in
	start)
		# Create cgroups
		sudo mkdir -p $CPU_GRP
		# sudo mkdir -p $RDT_GRP

		# Setup cgroups
		echo 11,35   | sudo tee -a $CPUS         > /dev/null
		echo 0       | sudo tee -a $MEMS         > /dev/null
		echo 1       | sudo tee -a $MIGRATE      > /dev/null
		# echo 0x3     | sudo tee -a $CACHE        > /dev/null

		# Start plumber
		# sudo cgexec -g cpuset,intel_rdt:plumber sudo ./Release/plumber $@
		for c in 11 35; do
			$CACHE_DRIVER -C $c 1
		done
		$CACHE_DRIVER -A 1 0 1

		for c in 0 24 1 25 2 26 3 27 4 28 5 29 6 30 7 31 8 32 9 33 10 34; do
			$CACHE_DRIVER -C $c 0
		done
		$CACHE_DRIVER -A 0 2 19

		sudo cgexec -g cpuset:plumber sudo ./Release/plumber $@
		
		sleep 1
		echo "Deamon PID: $(pidof plumber)"
		;;
	# cache) echo $1     | sudo tee -a $CACHE        > /dev/null ;;
	cpus)  echo $1     | sudo tee -a $CPUS        > /dev/null  ;;
	get-cpus) cat $CPUS ;;
	# echo "Plumber cache allocation: $(cat $CACHE)"
	log) sudo tail -f /tmp/plumber.log ;;
	pid)
		pids=$(pidof plumber)
		echo "$(pidof plumber | tr ' ' ,) (${#pids[@]})"
		;;
	kill)
		echo q | sudo tee -a $"/tmp/plumber" & > /dev/null
		sleep 1
		sudo kill -9 $(pidof plumber)
		pids=$(pidof plumber)
		echo "Plumber PIDs: $pids"
		;;
	clean)
		firstWay=$1
		lastWay=$2
		lines=$3
		rmid=$4
		for c in 0 24 1 25 2 26 3 27 4 28 5 29 6 30 7 31 8 32 9 33 10 34 11 35; do
			$CACHE_DRIVER -C $c 0
			$CACHE_DRIVER -R $c $rmid
		done
		$CACHE_DRIVER -A 0 $firstWay $lastWay

		echo "touch l $lines flush-before" | sudo tee -a $"/tmp/plumber" > /dev/null
		sleep 20
		echo "touch stop" | sudo tee -a $"/tmp/plumber" > /dev/null
		$CACHE_DRIVER -o $rmid
		;;
	perf-touch)
		timeSec=$1
		shift
		echo "touch $@" | sudo tee -a $"/tmp/plumber" > /dev/null

		sleep 15
		echo "Start perf-stat"
		sudo $PERF stat \
			-e LLC-loads-misses:u,LLC-loads:u \
			-e L1-dcache-loads:u,L1-dcache-load-misses:u \
			-p $(pidof plumber | tr ' ' ,) \
			-c sleep ${timeSec}
	 
		echo "touch stop" | sudo tee -a $"/tmp/plumber" > /dev/null
		;;
	perf-stat)
		timeSec=$1
		shift

		sudo .$PERF stat $@ \
			-e LLC-loads-misses:u,LLC-loads:u \
			-e L1-dcache-loads:u,L1-dcache-load-misses:u \
			-p $(pidof plumber | tr ' ' ,) \
			-c sleep ${timeSec}
		;;
	perf-top)
		sudo $PERF top \
			-e LLC-loads-misses:u,LLC-loads:u \
			-e L1-dcache-loads:u,L1-dcache-load-misses:u \
			-e cycles:u \
			-p $(pidof plumber | tr ' ' ,)
		;;
	*) echo $op $@ | sudo tee -a $"/tmp/plumber" > /dev/null ;;
esac
